# Usa una imagen base oficial de Python
FROM python:3.11-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

# Expone el puerto 80 para que esté disponible desde fuera del contenedor
EXPOSE 80

# Comando para ejecutar la aplicación
CMD ["python", "app.py"]
